# Generated by Django 5.1.1 on 2024-10-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_toy_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dawg',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
